server:
  port: 8085

spring:
  application:
    name: control-plane

  datasource:
    url: ${ARCHITRACE_DB_URL:jdbc:postgresql://localhost:5432/architrace}
    username: ${ARCHITRACE_DB_USERNAME:architrace}
    password: ${ARCHITRACE_DB_PASSWORD:architrace}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  grpc:
    server:
      transport: netty
      port: 9090
      address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
